myName = input("What is your name? ")
print("Hi " +myName+ ", can you tell me what your favourite starter, main course, dessert and drink is?")
input("Press Enter to continue...")
print("Let's start with starter")
favouritestarter = str(input("Type it here: "))
print("That's my favourite starter too!")
input("Press Enter to continue...")
print("Ok, now main course")
favouritemain = str(input("Type it here: "))
print("Great choice!")
input("Press Enter to continue...")
print("Moving on to dessert")
favouritedessert = str(input("Type it here: "))
print("All this talk of food is making me hungry!")
input("Press Enter to continue...")
print("Last but not least what is your favourite drink?")
favouritedrink = str(input("Type it here: "))
print("Nice!")
input("Press Enter to see what you chose...")
print("Thank you for sharing. Here is what you chose: For starter you chose " + favouritestarter + ", for the main course you chose " + favouritemain + ", for dessert you chose " + favouritedessert + " and finally for a choice of drink you chose" + favouritedrink + " .")